const img = {
  market: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1600&q=80",
  river: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1600&q=80",
  culture: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1600&q=80",
  nature: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=80",
  food: "https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=1600&q=80",
  night: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1600&q=80",
  street: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?auto=format&fit=crop&w=1600&q=80",
  cafe: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1600&q=80"
};

const guide = {
  default: "HeriLand Guide",
  food: "Food Guide",
  culture: "Culture Guide",
  nature: "Nature Guide",
  hidden: "Local Host"
};

const contactImage =
  "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80";

function gallery(main, second = img.river, third = img.nature) {
  return [main, second, third];
}

export const places = [
  {
    id: "sibu-waterfront",
    city: "sibu",
    category: "river",
    mood: "view",
    title: "第一次來 Sibu，可以先從河邊開始",
    name: "Sibu Waterfront",
    address: "Sibu Waterfront, Sibu, Sarawak",
    phone: "",
    hours: "全天開放",
    contactName: guide.default,
    contactImage,
    distance: "市中心",
    moodLabel: "河岸",
    score: "4.7",
    tags: ["系統推薦", "Sibu", "河岸", "散步"],
    image: img.river,
    images: gallery(img.river, img.street, img.nature),
    intro: "Sibu Waterfront 適合當作認識詩巫的第一站。這裡不用趕行程，慢慢看河、看人潮，也能感覺這座城市和 Rejang River 的關係。",
    services: ["河邊散步", "夕陽建議", "城市第一站", "可加入行程"]
  },
  {
    id: "rejang-esplanade",
    city: "sibu",
    category: "river",
    mood: "view",
    title: "想看 Sibu 的河流感，這裡很適合",
    name: "Rejang Esplanade",
    address: "Rejang Esplanade, Sibu, Sarawak",
    phone: "",
    hours: "全天開放",
    contactName: guide.default,
    contactImage,
    distance: "市中心",
    moodLabel: "河景",
    score: "4.6",
    tags: ["Sibu", "Rejang River", "散步", "夕陽"],
    image: img.river,
    images: gallery(img.river, img.nature, img.street),
    intro: "Rejang Esplanade 適合安排在傍晚，不一定要拍很多照片，只要沿著河邊慢慢走，就會感覺到 Sibu 的節奏。",
    services: ["夕陽路線", "慢走建議", "拍照角度", "附近景點推薦"]
  },
  {
  id: "sibu-lake-garden",
  city: "sibu",
  category: "nature",
  mood: "relax",
  title: "想找一個不用趕時間的地方，可以來這裡",
  name: "Sibu Lake Garden",
  address: "Sibu Lake Garden, Sibu, Sarawak",
  phone: "",
  hours: "全天開放",
  contactName: "Nature Guide",
  contactImage: contactImage,
  distance: "市區周邊",
  moodLabel: "公園",
  score: "4.5",
  tags: ["Sibu", "公園", "散步", "慢旅"],
  image: img.nature,
  images: gallery(
    img.nature,
    img.river,
    img.street
  ),
  intro:
    "Sibu Lake Garden 比較像當地人散步、運動和放空的地方。沒有很強的觀光感，但很適合慢慢待一下。",
  services: [
    "散步建議",
    "親子路線",
    "放鬆停留",
    "晨間推薦"
  ]
},
  {
    id: "sibu-town-square",
    city: "sibu",
    category: "city",
    mood: "relax",
    title: "想找一個城市中心的停留點，可以來這裡",
    name: "Sibu Town Square",
    address: "Sibu Town Square, Sibu, Sarawak",
    phone: "",
    hours: "全天開放",
    contactName: guide.default,
    contactImage,
    distance: "市中心",
    moodLabel: "城市廣場",
    score: "4.4",
    tags: ["Sibu", "城市", "廣場", "活動"],
    image: img.street,
    images: gallery(img.street, img.river, img.night),
    intro: "Sibu Town Square 是比較城市型的停留點，適合當作路線中轉，也適合觀察當地活動和城市生活感。",
    services: ["城市中轉", "活動查看", "休息停留", "附近路線"]
  },
  {
    id: "sibu-gateway",
    city: "sibu",
    category: "city",
    mood: "hidden",
    title: "不是必去景點，但很像城市的入口記憶",
    name: "Sibu Gateway",
    address: "Sibu Gateway, Sibu, Sarawak",
    phone: "",
    hours: "全天開放",
    contactName: guide.default,
    contactImage,
    distance: "市中心",
    moodLabel: "地標",
    score: "4.3",
    tags: ["Sibu", "地標", "城市入口", "拍照"],
    image: img.street,
    images: gallery(img.street, img.river, img.culture),
    intro: "Sibu Gateway 比較像城市入口的象徵，不一定要停很久，但適合放在城市散步路線裡，留下對 Sibu 的第一個印象。",
    services: ["拍照停留", "城市路線", "短暫停靠", "附近導覽"]
  },
  {
    id: "sibu-central-market",
    city: "sibu",
    category: "market",
    mood: "food",
    title: "想感受 Sibu 的日常，先從市場開始",
    name: "Sibu Central Market",
    address: "Sibu Central Market, Sibu, Sarawak",
    phone: "",
    hours: "早上至下午為主",
    contactName: guide.food,
    contactImage,
    distance: "市中心",
    moodLabel: "在地市場",
    score: "4.7",
    tags: ["系統推薦", "Sibu", "市場", "早餐"],
    image: img.market,
    images: gallery(img.market, img.food, img.street),
    intro: "Sibu Central Market 是認識詩巫很好的入口。這裡有熟食、蔬果、在地小吃，也能看到砂拉越日常生活的節奏。",
    services: ["早餐建議", "在地小吃推薦", "市場路線", "可加入行程"]
  },
  {
    id: "sibu-night-market",
    city: "sibu",
    category: "food",
    mood: "food",
    title: "晚上不知道吃什麼，來這裡最穩",
    name: "Sibu Night Market",
    address: "Jalan Market, Sibu, Sarawak",
    phone: "",
    hours: "傍晚至晚上",
    contactName: guide.food,
    contactImage,
    distance: "市中心",
    moodLabel: "夜市",
    score: "4.7",
    tags: ["系統推薦", "Sibu", "夜市", "晚餐"],
    image: img.night,
    images: gallery(img.night, img.market, img.food),
    intro: "Sibu Night Market 適合晚上慢慢逛，吃小吃、看攤位，也比較有在地生活感。",
    services: ["晚餐建議", "小吃推薦", "夜間路線", "附近散步"]
  },
  {
    id: "pasar-tamu-sibu",
    city: "sibu",
    category: "market",
    mood: "food",
    title: "想看更生活型的市場，可以找 Tamu 的節奏",
    name: "Pasar Tamu Sibu",
    address: "Sibu, Sarawak",
    phone: "",
    hours: "早上為主",
    contactName: guide.food,
    contactImage,
    distance: "市區周邊",
    moodLabel: "在地市集",
    score: "4.5",
    tags: ["Sibu", "Tamu", "市場", "在地生活"],
    image: img.market,
    images: gallery(img.market, img.street, img.food),
    intro: "Pasar Tamu 比較適合想看在地生活的人。這種地方不一定華麗，但會讓人更快理解一座城市平常怎麼運作。",
    services: ["市場探索", "在地生活", "早餐路線", "拍照提醒"]
  },
  {
    id: "sibu-fish-market",
    city: "sibu",
    category: "market",
    mood: "hidden",
    title: "想看更真實的 Sibu，魚市場很直接",
    name: "Sibu Fish Market",
    address: "Sibu, Sarawak",
    phone: "",
    hours: "清晨至上午為主",
    contactName: guide.hidden,
    contactImage,
    distance: "市區",
    moodLabel: "生活感",
    score: "4.4",
    tags: ["Sibu", "魚市場", "清晨", "生活感"],
    image: img.market,
    images: gallery(img.market, img.river, img.street),
    intro: "這不是典型觀光景點，但很適合 HeriLand。清晨的市場、人聲和交易感，會讓你看到更真實的 Sibu。",
    services: ["清晨路線", "在地觀察", "市場提醒", "小眾體驗"]
  },
  {
    id: "sibu-tua-pek-kong",
    city: "sibu",
    category: "culture",
    mood: "view",
    title: "看河景，也看見 Sibu 的華人歷史",
    name: "Tua Pek Kong Temple",
    address: "Jalan Temple, Sibu, Sarawak",
    phone: "",
    hours: "日間開放為主",
    contactName: guide.culture,
    contactImage,
    distance: "市中心",
    moodLabel: "文化",
    score: "4.8",
    tags: ["系統推薦", "Sibu", "廟宇", "河景"],
    image: img.culture,
    images: gallery(img.culture, img.river, img.street),
    intro: "位在 Rejang River 一帶，是 Sibu 很有代表性的地標。適合安排在傍晚前後，順路走河岸與市中心。",
    services: ["文化導覽", "河邊散步", "拍照建議", "附近路線推薦"]
  },
  {
    id: "sibu-heritage-centre",
    city: "sibu",
    category: "culture",
    mood: "hidden",
    title: "想了解 Sibu，不只是吃 Kampua",
    name: "Sibu Heritage Centre",
    address: "Sibu Town Centre, Sarawak",
    phone: "",
    hours: "日間開放為主",
    contactName: guide.culture,
    contactImage,
    distance: "市中心",
    moodLabel: "歷史",
    score: "4.6",
    tags: ["系統推薦", "Sibu", "歷史", "福州文化"],
    image: img.culture,
    images: gallery(img.culture, img.street, img.river),
    intro: "這裡適合放在 Sibu 行程一開始，先了解華人移民、原住民族群與 Rejang River Basin 的文化背景。",
    services: ["歷史簡介", "文化路線", "室內行程", "雨天備案"]
  },
  {
    id: "wong-nai-siong-memorial-park",
    city: "sibu",
    category: "culture",
    mood: "hidden",
    title: "想理解 Sibu 的福州背景，這裡值得放進路線",
    name: "Wong Nai Siong Memorial Park",
    address: "Sibu, Sarawak",
    phone: "",
    hours: "日間開放為主",
    contactName: guide.culture,
    contactImage,
    distance: "市區周邊",
    moodLabel: "福州文化",
    score: "4.5",
    tags: ["Sibu", "福州文化", "歷史", "紀念公園"],
    image: img.culture,
    images: gallery(img.culture, img.nature, img.street),
    intro: "Wong Nai Siong Memorial Park 適合放在文化路線裡。它不是熱鬧型景點，但能補上 Sibu 為什麼有這麼強福州味的背景。",
    services: ["文化背景", "歷史路線", "慢旅停留", "拍照建議"]
  },
  {
    id: "jade-dragon-temple",
    city: "sibu",
    category: "culture",
    mood: "view",
    title: "想看比較壯觀的廟宇，可以安排這裡",
    name: "Jade Dragon Temple",
    address: "Sibu, Sarawak",
    phone: "",
    hours: "日間開放為主",
    contactName: guide.culture,
    contactImage,
    distance: "市區周邊",
    moodLabel: "廟宇",
    score: "4.6",
    tags: ["Sibu", "廟宇", "文化", "拍照"],
    image: img.culture,
    images: gallery(img.culture, img.nature, img.river),
    intro: "Jade Dragon Temple 適合想看文化建築的人。這裡比市中心景點更有開闊感，也適合安排成半日路線的一站。",
    services: ["廟宇導覽", "拍照建議", "文化路線", "半日行程"]
  },
  {
    id: "lau-king-howe-hospital-memorial-museum",
    city: "sibu",
    category: "culture",
    mood: "hidden",
    title: "這不是熱門景點，但會讓 Sibu 更有故事",
    name: "Lau King Howe Hospital Memorial Museum",
    address: "Sibu, Sarawak",
    phone: "",
    hours: "日間開放為主",
    contactName: guide.culture,
    contactImage,
    distance: "市區",
    moodLabel: "小眾歷史",
    score: "4.4",
    tags: ["Sibu", "博物館", "歷史", "小眾"],
    image: img.culture,
    images: gallery(img.culture, img.street, img.market),
    intro: "這裡適合喜歡小眾歷史的人。它不是第一眼最吸引人的地方，但會讓你看到 Sibu 另一種很生活化的城市記憶。",
    services: ["室內行程", "歷史補充", "雨天備案", "小眾推薦"]
  },
  {
    id: "bukit-lima-nature-reserve",
    city: "sibu",
    category: "nature",
    mood: "relax",
    title: "想離開市區一下，這裡剛剛好",
    name: "Bukit Lima Nature Reserve",
    address: "Bukit Lima, Sibu, Sarawak",
    phone: "",
    hours: "早上至傍晚為主",
    contactName: guide.nature,
    contactImage,
    distance: "市區周邊",
    moodLabel: "自然",
    score: "4.5",
    tags: ["系統推薦", "Sibu", "森林", "散步"],
    image: img.nature,
    images: gallery(img.nature, img.culture, img.river),
    intro: "如果不想一直待在市中心，可以安排到 Bukit Lima 走走。比較適合慢旅、散步和看自然環境。",
    services: ["自然路線", "慢旅建議", "親子散步", "雨後提醒"]
  },
  {
    id: "kutien-memorial-park",
    city: "sibu",
    category: "nature",
    mood: "relax",
    title: "想找安靜一點的地方，可以試試這裡",
    name: "Kutien Memorial Park",
    address: "Sibu, Sarawak",
    phone: "",
    hours: "日間開放為主",
    contactName: guide.nature,
    contactImage,
    distance: "市區周邊",
    moodLabel: "公園",
    score: "4.3",
    tags: ["Sibu", "公園", "安靜", "散步"],
    image: img.nature,
    images: gallery(img.nature, img.street, img.river),
    intro: "Kutien Memorial Park 適合不想跑太多行程的時候。找一個比較安靜的地方走走，反而能感覺到小城的舒服。",
    services: ["休息停留", "散步路線", "安靜行程", "慢旅推薦"]
  },
  {
    id: "rejang-river-cruise",
    city: "sibu",
    category: "river",
    mood: "view",
    title: "如果想真正感覺 Rejang River，可以往船上走",
    name: "Rejang River Cruise",
    address: "Rejang River, Sibu, Sarawak",
    phone: "",
    hours: "依船班或行程而定",
    contactName: guide.default,
    contactImage,
    distance: "河岸區",
    moodLabel: "河流體驗",
    score: "4.6",
    tags: ["Sibu", "Rejang River", "船", "體驗"],
    image: img.river,
    images: gallery(img.river, img.nature, img.street),
    intro: "Rejang River 不只是背景，它是 Sibu 很重要的生活脈絡。搭船或安排河流體驗，會比只看照片更有感。",
    services: ["河流體驗", "行程提醒", "拍照建議", "安全提醒"]
  },
  {
    id: "igan-river-area",
    city: "sibu",
    category: "river",
    mood: "hidden",
    title: "想看比較小眾的河流生活，可以往這裡延伸",
    name: "Igan River Area",
    address: "Igan River Area, Sibu, Sarawak",
    phone: "",
    hours: "日間前往較適合",
    contactName: guide.hidden,
    contactImage,
    distance: "市區外圍",
    moodLabel: "小眾河岸",
    score: "4.2",
    tags: ["Sibu", "河流", "小眾", "慢旅"],
    image: img.river,
    images: gallery(img.river, img.nature, img.market),
    intro: "Igan River Area 比較適合想深入一點的人。這不是標準觀光路線，但能補上 Sibu 周邊河流生活的畫面。",
    services: ["小眾路線", "日間建議", "在地生活", "慢旅提醒"]
  },
{
  id: "kuching-waterfront",
  city: "kuching",
  category: "river",
  mood: "view",
  title: "第一次來 Kuching，可以先從河邊開始",
  name: "Kuching Waterfront",
  address: "Kuching Waterfront, Kuching, Sarawak",
  phone: "",
  hours: "全天開放",
  contactName: guide.default,
  contactImage,
  distance: "市中心",
  moodLabel: "河岸",
  score: "4.8",
  tags: ["系統推薦", "Kuching", "河岸", "散步"],
  image: img.river,
  images: gallery(img.river, img.street, img.night),
  intro: "Kuching Waterfront 是最適合進入古晉節奏的地方。白天可以看河岸，傍晚可以散步，晚上則能感覺城市慢慢亮起來。",
  services: ["河邊散步", "夕陽建議", "夜景路線", "可加入行程"]
},
{
  id: "darul-hana-bridge",
  city: "kuching",
  category: "river",
  mood: "view",
  title: "想看 Kuching 的城市夜景，可以走上這座橋",
  name: "Darul Hana Bridge",
  address: "Darul Hana Bridge, Kuching, Sarawak",
  phone: "",
  hours: "全天開放",
  contactName: guide.default,
  contactImage,
  distance: "市中心",
  moodLabel: "河景",
  score: "4.7",
  tags: ["Kuching", "橋", "夜景", "河岸"],
  image: img.river,
  images: gallery(img.river, img.night, img.street),
  intro: "Darul Hana Bridge 很適合安排在晚上。它不是單純過橋，而是能從另一個角度看 Kuching Waterfront 和河對岸的城市輪廓。",
  services: ["夜景建議", "拍照角度", "河岸路線", "散步推薦"]
},
{
  id: "main-bazaar",
  city: "kuching",
  category: "street",
  mood: "hidden",
  title: "想慢慢看古晉老街感，這裡很適合",
  name: "Main Bazaar",
  address: "Main Bazaar, Kuching, Sarawak",
  phone: "",
  hours: "日間至傍晚為主",
  contactName: guide.hidden,
  contactImage,
  distance: "市中心",
  moodLabel: "老街",
  score: "4.6",
  tags: ["Kuching", "老街", "手工藝", "慢旅"],
  image: img.street,
  images: gallery(img.street, img.culture, img.river),
  intro: "Main Bazaar 很適合慢慢走，不一定要買東西。老店、手工藝、街屋和河邊距離很近，是 Kuching 很有生活感的街區。",
  services: ["老街散步", "伴手禮建議", "拍照路線", "文化導覽"]
},
{
  id: "carpenter-street",
  city: "kuching",
  category: "street",
  mood: "hidden",
  title: "這條街不需要趕，慢慢走才有味道",
  name: "Carpenter Street",
  address: "Carpenter Street, Kuching, Sarawak",
  phone: "",
  hours: "日間至晚上",
  contactName: guide.hidden,
  contactImage,
  distance: "市中心",
  moodLabel: "老街",
  score: "4.7",
  tags: ["系統推薦", "Kuching", "老街", "咖啡店"],
  image: img.street,
  images: gallery(img.street, img.cafe, img.culture),
  intro: "Carpenter Street 是 Kuching 很有氛圍的街區。適合找咖啡店、看老建築，也適合當作城市散步的中段。",
  services: ["老街散步", "咖啡店推薦", "拍照建議", "附近路線"]
},
{
  id: "india-street",
  city: "kuching",
  category: "street",
  mood: "relax",
  title: "想看更日常的市區，可以走進 India Street",
  name: "India Street",
  address: "India Street, Kuching, Sarawak",
  phone: "",
  hours: "日間為主",
  contactName: guide.hidden,
  contactImage,
  distance: "市中心",
  moodLabel: "市集街區",
  score: "4.5",
  tags: ["Kuching", "街區", "市集", "在地生活"],
  image: img.street,
  images: gallery(img.street, img.market, img.cafe),
  intro: "India Street 比較像 Kuching 的日常街區。它不是最華麗的景點，但適合看人潮、店面和城市生活感。",
  services: ["街區散步", "購物建議", "生活感路線", "短暫停留"]
},
{
  id: "padungan-street",
  city: "kuching",
  category: "street",
  mood: "food",
  title: "想找古晉的老店和吃的，可以從這條街開始",
  name: "Padungan Street",
  address: "Padungan Street, Kuching, Sarawak",
  phone: "",
  hours: "日間至晚上",
  contactName: guide.food,
  contactImage,
  distance: "市區",
  moodLabel: "老店街區",
  score: "4.6",
  tags: ["Kuching", "老店", "美食", "街區"],
  image: img.street,
  images: gallery(img.street, img.food, img.cafe),
  intro: "Padungan Street 適合找老店、美食和比較自然的城市生活感。這裡不一定像熱門景點，但很適合慢慢探索。",
  services: ["老店推薦", "美食路線", "街區散步", "拍照建議"]
},
{
  id: "kuching-old-court-house",
  city: "kuching",
  category: "culture",
  mood: "hidden",
  title: "想看 Kuching 的殖民建築感，這裡可以停一下",
  name: "Kuching Old Court House",
  address: "Kuching Old Court House, Kuching, Sarawak",
  phone: "",
  hours: "日間開放為主",
  contactName: guide.culture,
  contactImage,
  distance: "市中心",
  moodLabel: "歷史建築",
  score: "4.6",
  tags: ["Kuching", "歷史", "建築", "文化"],
  image: img.culture,
  images: gallery(img.culture, img.street, img.river),
  intro: "Old Court House 是 Kuching 很有歷史感的建築。適合放在 Waterfront 和老街路線中間，不用待很久，但能補上城市背景。",
  services: ["歷史導覽", "建築拍照", "城市散步", "附近路線"]
},
{
  id: "square-tower-kuching",
  city: "kuching",
  category: "culture",
  mood: "view",
  title: "河邊旁的小地標，很適合順路看看",
  name: "Square Tower",
  address: "Square Tower, Kuching Waterfront, Sarawak",
  phone: "",
  hours: "日間開放為主",
  contactName: guide.culture,
  contactImage,
  distance: "Waterfront 周邊",
  moodLabel: "河岸地標",
  score: "4.4",
  tags: ["Kuching", "地標", "河岸", "歷史"],
  image: img.culture,
  images: gallery(img.culture, img.river, img.street),
  intro: "Square Tower 適合當作 Waterfront 散步時的順路點。它不大，但能讓河邊路線更有歷史層次。",
  services: ["順路景點", "拍照建議", "河岸導覽", "短暫停留"]
},
{
  id: "brooke-gallery",
  city: "kuching",
  category: "culture",
  mood: "hidden",
  title: "想了解白人拉惹時期，可以把這裡放進路線",
  name: "Brooke Gallery",
  address: "Fort Margherita, Kuching, Sarawak",
  phone: "",
  hours: "日間開放為主",
  contactName: guide.culture,
  contactImage,
  distance: "河對岸",
  moodLabel: "歷史",
  score: "4.6",
  tags: ["Kuching", "Brooke", "歷史", "文化"],
  image: img.culture,
  images: gallery(img.culture, img.river, img.street),
  intro: "Brooke Gallery 適合想理解 Kuching 歷史的人。它讓城市不只是河邊散步，而是開始有更深的故事背景。",
  services: ["歷史路線", "文化導覽", "河對岸行程", "室內景點"]
},
{
  id: "sarawak-river-cruise",
  city: "kuching",
  category: "river",
  mood: "view",
  title: "想用比較舒服的方式看 Kuching，可以上船",
  name: "Sarawak River Cruise",
  address: "Sarawak River, Kuching, Sarawak",
  phone: "",
  hours: "依船班而定",
  contactName: guide.default,
  contactImage,
  distance: "Waterfront",
  moodLabel: "河流體驗",
  score: "4.7",
  tags: ["Kuching", "遊船", "夕陽", "河景"],
  image: img.river,
  images: gallery(img.river, img.night, img.street),
  intro: "Sarawak River Cruise 很適合傍晚安排。不是為了趕景點，而是用慢一點的方式看河、城市和天空變化。",
  services: ["遊船建議", "夕陽時段", "拍照提醒", "行程安排"]
},
{
  id: "chinese-history-museum-kuching",
  city: "kuching",
  category: "culture",
  mood: "hidden",
  title: "想了解古晉華人背景，可以從這裡開始",
  name: "Chinese History Museum",
  address: "Waterfront, Kuching, Sarawak",
  phone: "",
  hours: "日間開放為主",
  contactName: guide.culture,
  contactImage,
  distance: "Waterfront",
  moodLabel: "文化",
  score: "4.5",
  tags: ["Kuching", "華人歷史", "博物館", "文化"],
  image: img.culture,
  images: gallery(img.culture, img.street, img.river),
  intro: "Chinese History Museum 不大，但很適合補上 Kuching 的華人文化背景。放在 Waterfront 路線中很自然。",
  services: ["文化補充", "室內行程", "雨天備案", "城市導覽"]
},
{
  id: "sarawak-museum",
  city: "kuching",
  category: "culture",
  mood: "hidden",
  title: "想認識砂拉越，不該只看城市表面",
  name: "Sarawak Museum",
  address: "Sarawak Museum, Kuching, Sarawak",
  phone: "",
  hours: "日間開放為主",
  contactName: guide.culture,
  contactImage,
  distance: "市中心",
  moodLabel: "博物館",
  score: "4.7",
  tags: ["Kuching", "砂拉越", "博物館", "文化"],
  image: img.culture,
  images: gallery(img.culture, img.nature, img.street),
  intro: "Sarawak Museum 適合放在 Kuching 的文化路線。它能讓旅程不只是吃和拍照，而是開始理解砂拉越本身。",
  services: ["文化導覽", "室內行程", "雨天備案", "歷史補充"]
},
{
  id: "borneo-cultures-museum",
  city: "kuching",
  category: "culture",
  mood: "hidden",
  title: "想一次理解婆羅洲文化，這裡很值得排",
  name: "Borneo Cultures Museum",
  address: "Borneo Cultures Museum, Kuching, Sarawak",
  phone: "",
  hours: "日間開放為主",
  contactName: guide.culture,
  contactImage,
  distance: "市中心",
  moodLabel: "文化博物館",
  score: "4.9",
  tags: ["系統推薦", "Kuching", "Borneo", "文化"],
  image: img.culture,
  images: gallery(img.culture, img.nature, img.street),
  intro: "Borneo Cultures Museum 很適合第一次來砂拉越的人。它不是普通展館，而是能幫你快速建立對婆羅洲文化的理解。",
  services: ["文化導覽", "室內行程", "親子推薦", "雨天備案"]
},
{
  id: "tua-pek-kong-kuching",
  city: "kuching",
  category: "culture",
  mood: "view",
  title: "古晉市中心很有代表性的廟宇地標",
  name: "Tua Pek Kong Temple",
  address: "Tua Pek Kong Temple, Kuching, Sarawak",
  phone: "",
  hours: "日間開放為主",
  contactName: guide.culture,
  contactImage,
  distance: "市中心",
  moodLabel: "廟宇",
  score: "4.6",
  tags: ["Kuching", "廟宇", "華人文化", "市中心"],
  image: img.culture,
  images: gallery(img.culture, img.street, img.river),
  intro: "Kuching 的 Tua Pek Kong Temple 很適合順路停留。它靠近市區與河岸，是理解古晉華人生活痕跡的一個入口。",
  services: ["文化路線", "市中心散步", "拍照建議", "短暫停留"]
},
{
  id: "fort-margherita",
  city: "kuching",
  category: "culture",
  mood: "view",
  title: "想從河對岸看 Kuching 的歷史，可以來這裡",
  name: "Fort Margherita",
  address: "Fort Margherita, Kuching, Sarawak",
  phone: "",
  hours: "日間開放為主",
  contactName: guide.culture,
  contactImage,
  distance: "河對岸",
  moodLabel: "古堡",
  score: "4.6",
  tags: ["Kuching", "古堡", "歷史", "河景"],
  image: img.culture,
  images: gallery(img.culture, img.river, img.street),
  intro: "Fort Margherita 適合和 Darul Hana Bridge、Brooke Gallery 一起安排。走到河對岸後，Kuching 會變成另一種視角。",
  services: ["歷史導覽", "河對岸路線", "拍照建議", "半日行程"]
},
{
  id: "the-astana-kuching",
  city: "kuching",
  category: "culture",
  mood: "view",
  title: "不一定進得去，但遠遠看也有城市感",
  name: "The Astana",
  address: "The Astana, Kuching, Sarawak",
  phone: "",
  hours: "外觀欣賞為主",
  contactName: guide.culture,
  contactImage,
  distance: "河對岸",
  moodLabel: "地標",
  score: "4.4",
  tags: ["Kuching", "Astana", "河對岸", "地標"],
  image: img.river,
  images: gallery(img.river, img.culture, img.street),
  intro: "The Astana 多數時候比較適合遠觀。從 Waterfront 或橋上看過去，會讓 Kuching 的河岸景色更完整。",
  services: ["外觀欣賞", "拍照角度", "河岸路線", "城市導覽"]
},
{
  id: "cat-museum-kuching",
  city: "kuching",
  category: "culture",
  mood: "relax",
  title: "想找一個輕鬆又有記憶點的地方，可以來貓博物館",
  name: "Cat Museum",
  address: "Cat Museum, Kuching, Sarawak",
  phone: "",
  hours: "日間開放為主",
  contactName: guide.default,
  contactImage,
  distance: "市區周邊",
  moodLabel: "輕鬆景點",
  score: "4.4",
  tags: ["Kuching", "貓", "博物館", "親子"],
  image: img.culture,
  images: gallery(img.culture, img.street, img.nature),
  intro: "Cat Museum 很適合放在輕鬆行程裡。它不是嚴肅景點，但和 Kuching 這座貓城的形象很搭。",
  services: ["親子推薦", "輕鬆行程", "拍照建議", "雨天備案"]
},
{
  id: "textile-museum-kuching",
  city: "kuching",
  category: "culture",
  mood: "hidden",
  title: "想看砂拉越的紋理和工藝，可以進來慢慢看",
  name: "Textile Museum",
  address: "Textile Museum, Kuching, Sarawak",
  phone: "",
  hours: "日間開放為主",
  contactName: guide.culture,
  contactImage,
  distance: "市中心",
  moodLabel: "工藝文化",
  score: "4.4",
  tags: ["Kuching", "紡織", "工藝", "文化"],
  image: img.culture,
  images: gallery(img.culture, img.street, img.market),
  intro: "Textile Museum 適合喜歡文化細節的人。布料、紋樣和工藝會讓砂拉越的文化變得更具體。",
  services: ["工藝導覽", "室內行程", "文化補充", "雨天備案"]
},
{
  id: "bako-national-park",
  city: "kuching",
  category: "nature",
  mood: "relax",
  title: "想看砂拉越自然感，Bako 很適合排一天",
  name: "Bako National Park",
  address: "Bako National Park, Kuching, Sarawak",
  phone: "",
  hours: "日間行程為主",
  contactName: guide.nature,
  contactImage,
  distance: "市區外圍",
  moodLabel: "自然公園",
  score: "4.8",
  tags: ["系統推薦", "Kuching", "自然", "國家公園"],
  image: img.nature,
  images: gallery(img.nature, img.river, img.street),
  intro: "Bako National Park 適合想把 Kuching 從城市延伸到自然的人。這裡需要多一點時間，但會讓旅程更完整。",
  services: ["一日行程", "自然路線", "安全提醒", "交通建議"]
},
{
  id: "santubong-beach",
  city: "kuching",
  category: "nature",
  mood: "relax",
  title: "想離開市區看海，可以往 Santubong 走",
  name: "Santubong Beach",
  address: "Santubong, Kuching, Sarawak",
  phone: "",
  hours: "日間至傍晚",
  contactName: guide.nature,
  contactImage,
  distance: "市區外圍",
  moodLabel: "海邊",
  score: "4.6",
  tags: ["Kuching", "Santubong", "海邊", "放空"],
  image: img.nature,
  images: gallery(img.nature, img.river, img.street),
  intro: "Santubong Beach 適合不想待在市區的人。海風、山影和比較慢的節奏，會讓 Kuching 變得更開闊。",
  services: ["海邊路線", "傍晚建議", "慢旅停留", "拍照建議"]
},
{
  id: "damai-beach",
  city: "kuching",
  category: "nature",
  mood: "relax",
  title: "想把古晉行程變慢，Damai 很適合",
  name: "Damai Beach",
  address: "Damai, Kuching, Sarawak",
  phone: "",
  hours: "日間至傍晚",
  contactName: guide.nature,
  contactImage,
  distance: "市區外圍",
  moodLabel: "海邊慢旅",
  score: "4.6",
  tags: ["Kuching", "Damai", "海邊", "度假感"],
  image: img.nature,
  images: gallery(img.nature, img.river, img.cafe),
  intro: "Damai Beach 比較適合安排半日或一日慢旅。這裡不是趕景點，而是讓旅行節奏放慢。",
  services: ["半日行程", "海邊散步", "放空建議", "夕陽提醒"]
},
{
  id: "mount-santubong",
  city: "kuching",
  category: "nature",
  mood: "view",
  title: "想看更壯一點的自然感，可以把 Santubong 放進清單",
  name: "Mount Santubong",
  address: "Mount Santubong, Kuching, Sarawak",
  phone: "",
  hours: "日間登山為主",
  contactName: guide.nature,
  contactImage,
  distance: "市區外圍",
  moodLabel: "山景",
  score: "4.7",
  tags: ["Kuching", "Santubong", "登山", "自然"],
  image: img.nature,
  images: gallery(img.nature, img.river, img.street),
  intro: "Mount Santubong 適合喜歡自然和體力型路線的人。它讓 Kuching 不只是河邊城市，也有山與海的輪廓。",
  services: ["登山提醒", "自然路線", "安全建議", "半日行程"]
},
{
  id: "semenggoh-wildlife-centre",
  city: "kuching",
  category: "nature",
  mood: "relax",
  title: "想看砂拉越自然與動物，這裡很適合",
  name: "Semenggoh Wildlife Centre",
  address: "Semenggoh Wildlife Centre, Kuching, Sarawak",
  phone: "",
  hours: "日間開放為主",
  contactName: guide.nature,
  contactImage,
  distance: "市區外圍",
  moodLabel: "自然保育",
  score: "4.8",
  tags: ["系統推薦", "Kuching", "野生動物", "自然"],
  image: img.nature,
  images: gallery(img.nature, img.street, img.culture),
  intro: "Semenggoh Wildlife Centre 適合想看砂拉越自然保育的人。比起一般動物景點，它更像是理解婆羅洲自然的一個入口。",
  services: ["自然導覽", "親子推薦", "開放時間提醒", "交通建議"]
},
{
  id: "kubah-national-park",
  city: "kuching",
  category: "nature",
  mood: "relax",
  title: "如果想找森林和瀑布感，可以考慮 Kubah",
  name: "Kubah National Park",
  address: "Kubah National Park, Kuching, Sarawak",
  phone: "",
  hours: "日間行程為主",
  contactName: guide.nature,
  contactImage,
  distance: "市區外圍",
  moodLabel: "森林",
  score: "4.6",
  tags: ["Kuching", "森林", "國家公園", "自然"],
  image: img.nature,
  images: gallery(img.nature, img.river, img.street),
  intro: "Kubah National Park 適合想從城市切換到森林的人。這裡比較適合有一點時間、想走自然路線的旅人。",
  services: ["森林路線", "一日行程", "安全提醒", "雨後提醒"]
},
{
  id: "fairy-cave",
  city: "kuching",
  category: "nature",
  mood: "hidden",
  title: "想看比較有探險感的自然景點，可以去 Fairy Cave",
  name: "Fairy Cave",
  address: "Fairy Cave, Bau, Sarawak",
  phone: "",
  hours: "日間開放為主",
  contactName: guide.nature,
  contactImage,
  distance: "Kuching 周邊",
  moodLabel: "洞穴",
  score: "4.7",
  tags: ["Kuching", "Bau", "洞穴", "自然"],
  image: img.nature,
  images: gallery(img.nature, img.culture, img.river),
  intro: "Fairy Cave 適合想看不同地貌的人。它距離市區較遠，但能讓 Kuching 行程變得更有探索感。",
  services: ["周邊行程", "安全提醒", "拍照建議", "自然路線"]
},
{
  id: "wind-cave",
  city: "kuching",
  category: "nature",
  mood: "hidden",
  title: "想安排洞穴路線，可以和 Fairy Cave 一起看",
  name: "Wind Cave",
  address: "Wind Cave, Bau, Sarawak",
  phone: "",
  hours: "日間開放為主",
  contactName: guide.nature,
  contactImage,
  distance: "Kuching 周邊",
  moodLabel: "洞穴",
  score: "4.5",
  tags: ["Kuching", "Bau", "洞穴", "自然"],
  image: img.nature,
  images: gallery(img.nature, img.river, img.street),
  intro: "Wind Cave 適合和 Fairy Cave 做成同一條路線。這類景點會讓 Kuching 不只是城市，而是連到周邊自然探索。",
  services: ["洞穴路線", "周邊行程", "安全提醒", "交通建議"]
},
{
  id: "orchid-garden-kuching",
  city: "kuching",
  category: "nature",
  mood: "relax",
  title: "想找安靜一點的花園，可以來這裡",
  name: "Orchid Garden",
  address: "Orchid Garden, Kuching, Sarawak",
  phone: "",
  hours: "日間開放為主",
  contactName: guide.nature,
  contactImage,
  distance: "河對岸",
  moodLabel: "花園",
  score: "4.4",
  tags: ["Kuching", "花園", "安靜", "散步"],
  image: img.nature,
  images: gallery(img.nature, img.culture, img.river),
  intro: "Orchid Garden 適合放在比較輕鬆的行程。它不需要太多體力，也適合和河對岸路線一起安排。",
  services: ["花園散步", "親子推薦", "拍照建議", "短暫停留"]
},
{
  id: "topspot-food-court",
  city: "kuching",
  category: "food",
  mood: "food",
  title: "晚上想吃海鮮，Topspot 很適合",
  name: "Topspot Food Court",
  address: "Topspot Food Court, Kuching, Sarawak",
  phone: "",
  hours: "傍晚至晚上",
  contactName: guide.food,
  contactImage,
  distance: "市中心",
  moodLabel: "海鮮美食",
  score: "4.6",
  tags: ["系統推薦", "Kuching", "海鮮", "晚餐"],
  image: img.food,
  images: gallery(img.food, img.night, img.market),
  intro: "Topspot Food Court 很適合晚上安排。想吃海鮮又不想太正式，這裡會比餐廳更有熱鬧感。",
  services: ["晚餐推薦", "海鮮建議", "夜間路線", "附近散步"]
},
{
  id: "kuching-night-market",
  city: "kuching",
  category: "food",
  mood: "food",
  title: "想找晚上吃的和生活感，可以逛夜市",
  name: "Kuching Night Market",
  address: "Kuching, Sarawak",
  phone: "",
  hours: "傍晚至晚上",
  contactName: guide.food,
  contactImage,
  distance: "市區",
  moodLabel: "夜市",
  score: "4.5",
  tags: ["Kuching", "夜市", "小吃", "晚餐"],
  image: img.night,
  images: gallery(img.night, img.food, img.market),
  intro: "Kuching Night Market 適合想看夜間生活的人。比起正式景點，它更像城市晚上自然發生的日常。",
  services: ["夜市小吃", "晚餐建議", "夜間散步", "小眾推薦"]
},
{
  id: "open-air-market-kuching",
  city: "kuching",
  category: "market",
  mood: "food",
  title: "想吃比較在地的，可以找 Open Air Market",
  name: "Open Air Market",
  address: "Open Air Market, Kuching, Sarawak",
  phone: "",
  hours: "日間至晚上",
  contactName: guide.food,
  contactImage,
  distance: "市中心",
  moodLabel: "在地市場",
  score: "4.5",
  tags: ["Kuching", "市場", "小吃", "在地"],
  image: img.market,
  images: gallery(img.market, img.food, img.street),
  intro: "Open Air Market 適合找比較在地的吃法。這裡不需要太精緻，重點是自然、方便、有城市生活感。",
  services: ["在地小吃", "早餐午餐", "市場路線", "附近導覽"]
},
{
  id: "waterfront-night-walk-kuching",
  city: "kuching",
  category: "river",
  mood: "view",
  title: "晚上不想跑太遠，河邊散步就很好",
  name: "Waterfront Night Walk",
  address: "Kuching Waterfront, Kuching, Sarawak",
  phone: "",
  hours: "晚上較適合",
  contactName: guide.default,
  contactImage,
  distance: "市中心",
  moodLabel: "夜間散步",
  score: "4.8",
  tags: ["Kuching", "夜景", "散步", "河岸"],
  image: img.night,
  images: gallery(img.night, img.river, img.street),
  intro: "Waterfront Night Walk 是 Kuching 很舒服的晚上路線。不用安排太多，只要慢慢走、看燈光和人潮，就很有旅行感。",
  services: ["夜間路線", "拍照建議", "散步推薦", "安全提醒"]
},
{
  id: "jalan-song-food-street",
  city: "kuching",
  category: "food",
  mood: "food",
  title: "想找熱鬧一點的晚餐，可以往 Jalan Song",
  name: "Jalan Song Food Street",
  address: "Jalan Song, Kuching, Sarawak",
  phone: "",
  hours: "傍晚至晚上",
  contactName: guide.food,
  contactImage,
  distance: "市區",
  moodLabel: "晚餐街區",
  score: "4.5",
  tags: ["Kuching", "美食街", "晚餐", "夜生活"],
  image: img.food,
  images: gallery(img.food, img.night, img.cafe),
  intro: "Jalan Song Food Street 適合晚上想找吃的時候。它比較偏生活型，不是觀光打卡，而是當地人會自然去吃東西的區域。",
  services: ["晚餐推薦", "夜間路線", "在地餐廳", "附近導覽"]
}
];

export const foods = [
  {
    id: "sibu-kampua-mee",
    city: "sibu",
    name: "Kampua Mee",
    location: "Sibu",
    tag: "#詩巫代表美食",
    desc: "Sibu 最具代表性的乾麵之一，簡單、直接，很適合當作認識詩巫早餐的第一口。",
    image: img.food
  },
  {
    id: "sibu-kompia",
    city: "sibu",
    name: "Kompia",
    location: "Sibu",
    tag: "#福州光餅",
    desc: "帶有福州背景的特色小吃，可以單吃，也常見夾肉版本。",
    image: "https://images.unsplash.com/photo-1608198093002-ad4e005484ec?auto=format&fit=crop&w=900&q=80"
  },
  {
    id: "sibu-dian-bian-hu",
    city: "sibu",
    name: "Dian Bian Hu",
    location: "Sibu",
    tag: "#鼎邊糊",
    desc: "帶有福州味的在地食物，適合想找 Sibu 文化味的人。",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=900&q=80"
  },
  {
    id: "sibu-dabai",
    city: "sibu",
    name: "Dabai",
    location: "Sibu",
    tag: "#砂拉越特色食材",
    desc: "砂拉越特色食材之一，季節感很強，很適合做地方內容介紹。",
    image: "https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=900&q=80"
  },
  {
    id: "sibu-laksa",
    city: "sibu",
    name: "Sibu Laksa",
    location: "Sibu",
    tag: "#在地早餐",
    desc: "和 Kuching Laksa 不同，Sibu 的版本可以作為早餐探索的一部分。",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=80"
  },
  {
    id: "red-wine-mee-sua",
    city: "sibu",
    name: "Red Wine Mee Sua",
    location: "Sibu",
    tag: "#福州風味",
    desc: "紅酒麵線帶有很強的福州家庭料理感，很適合放在文化美食路線。",
    image: "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&w=900&q=80"
  },
  {
    id: "roti-kahwin",
    city: "sibu",
    name: "Roti Kahwin",
    location: "Sibu",
    tag: "#咖啡店早餐",
    desc: "咖啡店常見早餐，適合和咖啡、半熟蛋一起出現。",
    image: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=900&q=80"
  },
  {
    id: "half-boiled-eggs-breakfast",
    city: "sibu",
    name: "半熟蛋早餐",
    location: "Sibu",
    tag: "#南洋早餐",
    desc: "半熟蛋、咖啡和烤麵包，是很適合做在地早餐情境的內容。",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=80"
  },
  {
    id: "kompia-with-meat",
    city: "sibu",
    name: "光餅夾肉",
    location: "Sibu",
    tag: "#福州小吃",
    desc: "比單純光餅更有飽足感，很適合作為小吃或下午點心。",
    image: "https://images.unsplash.com/photo-1608198093002-ad4e005484ec?auto=format&fit=crop&w=900&q=80"
  },
  {
    id: "sibu-fried-cooked-noodles",
    city: "sibu",
    name: "炒煮",
    location: "Sibu",
    tag: "#在地麵食",
    desc: "名字很生活化，適合放進 HeriLand 的在地美食字典。",
    image: "https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=900&q=80"
  },
  {
    id: "sarawak-kopitiam-breakfast",
    city: "sibu",
    name: "砂拉越咖啡店早餐",
    location: "Sibu",
    tag: "#生活感早餐",
    desc: "不是單一道菜，而是一種早上的城市節奏：咖啡、麵、麵包、半熟蛋。",
    image: img.cafe
  },
  {
    id: "foochow-dry-noodles",
    city: "sibu",
    name: "福州乾麵",
    location: "Sibu",
    tag: "#福州味",
    desc: "可以和 Kampua Mee 放在同一條美食脈絡裡，強化 Sibu 的福州文化感。",
    image: img.food
  },
  {
    id: "night-market-grilled-skewers",
    city: "sibu",
    name: "夜市烤串",
    location: "Sibu Night Market",
    tag: "#夜市小吃",
    desc: "晚上逛夜市時很容易出現的選擇，適合做夜間推薦。",
    image: img.night
  },
  {
    id: "sarawak-fried-snacks",
    city: "sibu",
    name: "砂拉越炸物",
    location: "Sibu",
    tag: "#小吃",
    desc: "適合放在夜市、小攤、下午茶類型的推薦裡。",
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=900&q=80"
  },
  {
    id: "riverside-snacks",
    city: "sibu",
    name: "河邊小吃",
    location: "Sibu Waterfront",
    tag: "#河邊散步",
    desc: "不一定是固定店家，而是河邊散步時可以搭配的輕食情境。",
    image: img.market
  },
  {
    id: "night-market-dessert",
    city: "sibu",
    name: "夜市糖水",
    location: "Sibu Night Market",
    tag: "#飯後甜點",
    desc: "逛完夜市後適合收尾的小甜點，也適合放進晚上路線。",
    image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=900&q=80"
  },
{
  id: "kuching-sarawak-laksa",
  city: "kuching",
  name: "Sarawak Laksa",
  location: "Kuching",
  tag: "#古晉代表美食",
  desc: "第一次來 Kuching，很適合從 Sarawak Laksa 開始。它不是單純早餐，而是很多人對砂拉越味道的第一個記憶點。",
  image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=80"
},
{
  id: "kuching-kolo-mee",
  city: "kuching",
  name: "Kolo Mee",
  location: "Kuching",
  tag: "#古晉乾麵",
  desc: "Kolo Mee 簡單但很有在地味道，適合放在早餐或午餐路線。",
  image: img.food
},
{
  id: "kuching-midin-belacan",
  city: "kuching",
  name: "Midin Belacan",
  location: "Kuching",
  tag: "#砂拉越野菜",
  desc: "Midin 是砂拉越很有代表性的野菜，配上 belacan 會很有地方味。",
  image: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=900&q=80"
},
{
  id: "kuching-manok-pansoh",
  city: "kuching",
  name: "Manok Pansoh",
  location: "Kuching",
  tag: "#傳統料理",
  desc: "Manok Pansoh 是竹筒雞料理，適合用來介紹砂拉越的傳統飲食文化。",
  image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=900&q=80"
},
{
  id: "kuching-tomato-kueh-tiaw",
  city: "kuching",
  name: "Tomato Kueh Tiaw",
  location: "Kuching",
  tag: "#古晉特色",
  desc: "Tomato Kueh Tiaw 是 Kuching 很有辨識度的食物，適合想找不同口味的人。",
  image: "https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=900&q=80"
},
{
  id: "kuching-kek-lapis",
  city: "kuching",
  name: "Kek Lapis",
  location: "Kuching",
  tag: "#砂拉越千層糕",
  desc: "Kek Lapis 很適合作為伴手禮，也很適合放進 Kuching 的甜點與文化內容。",
  image: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=900&q=80"
},
{
  id: "kuching-kaya-toast",
  city: "kuching",
  name: "Kaya Toast",
  location: "Kuching",
  tag: "#咖啡店早餐",
  desc: "Kaya Toast 適合和咖啡、半熟蛋一起出現，是很自然的南洋早餐情境。",
  image: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=900&q=80"
},
{
  id: "kuching-half-boiled-egg-breakfast",
  city: "kuching",
  name: "Half-Boiled Egg Breakfast",
  location: "Kuching",
  tag: "#南洋早餐",
  desc: "半熟蛋早餐不是一道華麗料理，但很適合建立 Kuching 的早晨生活感。",
  image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=80"
},
{
  id: "kuching-kampua-style-noodles",
  city: "kuching",
  name: "Kampua Style Noodles",
  location: "Kuching",
  tag: "#乾麵早餐",
  desc: "雖然 Kampua 更常和 Sibu 連在一起，但在 Kuching 也能找到類似乾麵早餐的生活感。",
  image: img.food
},
{
  id: "kuching-curry-rice",
  city: "kuching",
  name: "Curry Rice",
  location: "Kuching",
  tag: "#在地午餐",
  desc: "Curry Rice 很適合做成午餐推薦，不一定是觀光美食，但很有日常感。",
  image: "https://images.unsplash.com/photo-1604908177522-4020f53e0d4d?auto=format&fit=crop&w=900&q=80"
},
{
  id: "kuching-satay",
  city: "kuching",
  name: "Satay",
  location: "Kuching",
  tag: "#夜市小吃",
  desc: "Satay 適合放在夜市、晚餐或河邊散步後的小吃推薦裡。",
  image: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=900&q=80"
},
{
  id: "kuching-bbq-seafood",
  city: "kuching",
  name: "BBQ Seafood",
  location: "Kuching",
  tag: "#晚餐海鮮",
  desc: "BBQ Seafood 適合搭配 Topspot 或晚餐路線，是 Kuching 晚上很容易出現的選擇。",
  image: "https://images.unsplash.com/photo-1559737558-2f5a35f4523b?auto=format&fit=crop&w=900&q=80"
},
{
  id: "kuching-sugar-cane-drink",
  city: "kuching",
  name: "Sugar Cane Drink",
  location: "Kuching",
  tag: "#消暑飲料",
  desc: "天氣熱的時候，甘蔗水很適合放進街區和市場路線。",
  image: "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&w=900&q=80"
},
{
  id: "kuching-cendol",
  city: "kuching",
  name: "Cendol",
  location: "Kuching",
  tag: "#飯後甜點",
  desc: "Cendol 適合放在午後或吃完正餐後，是很有南洋感的甜品。",
  image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=900&q=80"
},
{
  id: "kuching-apam-balik",
  city: "kuching",
  name: "Apam Balik",
  location: "Kuching",
  tag: "#街邊小吃",
  desc: "Apam Balik 適合出現在夜市或小攤內容裡，簡單但很有生活感。",
  image: "https://images.unsplash.com/photo-1608198093002-ad4e005484ec?auto=format&fit=crop&w=900&q=80"
},
{
  id: "kuching-black-bean-coffee",
  city: "kuching",
  name: "Black Bean Coffee",
  location: "Kuching",
  tag: "#咖啡慢旅",
  desc: "Black Bean Coffee 適合做成 Kuching 的咖啡店慢旅內容，讓城市不只是景點，也有停下來的地方。",
  image: img.cafe
},
{
  id: "kuching-old-town-cafe",
  city: "kuching",
  name: "Old Town Cafe",
  location: "Kuching",
  tag: "#老街咖啡",
  desc: "老街咖啡店適合安排在 Carpenter Street 或 Main Bazaar 路線中間。",
  image: img.cafe
},
{
  id: "kuching-riverfront-cafe",
  city: "kuching",
  name: "Riverfront Cafe",
  location: "Kuching Waterfront",
  tag: "#河邊咖啡",
  desc: "Riverfront Cafe 適合想靠近河邊坐一下的人，尤其適合午後或傍晚。",
  image: img.cafe
},
{
  id: "kuching-carpenter-street-cafe",
  city: "kuching",
  name: "Carpenter Street Cafe",
  location: "Carpenter Street",
  tag: "#街區咖啡",
  desc: "Carpenter Street 的咖啡店很適合讓旅程放慢，也能把老街和現代感接起來。",
  image: img.cafe
},
{
  id: "kuching-local-kopitiam",
  city: "kuching",
  name: "Local Kopitiam",
  location: "Kuching",
  tag: "#在地咖啡店",
  desc: "Local Kopitiam 是 Kuching 很重要的日常場景，適合早餐、咖啡和聊天。",
  image: img.cafe
}
];

export const cities = [
  {
    id: "kuching",
    name: "Kuching",
    tag: "#城市散步",
    intro: "砂拉越最適合第一次慢慢認識的城市。",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "miri",
    name: "Miri",
    tag: "#海邊夕陽",
    intro: "適合海邊、夕陽與自然路線。",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "sibu",
    name: "Sibu",
    tag: "#福州美食",
    intro: "Sibu 是砂拉越中部的重要城市，適合用市場、美食、河岸與文化慢慢認識。",
    image: img.market
  },
  {
    id: "bintulu",
    name: "Bintulu",
    tag: "#自然慢旅",
    intro: "適合自然、海邊與工業城市之外的生活感探索。",
    image: img.nature
  },
  {
    id: "sarikei",
    name: "Sarikei",
    tag: "#小城生活",
    intro: "節奏比較慢，適合做小城生活感內容。",
    image: img.river
  }
];

export const spots = places.map(place => ({
  id: place.id,
  city: place.city,
  name: place.name,
  location: place.address || place.city,
  image: place.image
}));

export const reviews = [
  {
    id: "review-sibu-market",
    city: "sibu",
    name: "Alicia",
    achievement: "收藏了 32 個在地市場",
    title: "Sibu 的市場比我想像中有生活感",
    description: "不是單純買東西的地方，而是很快能看懂一座城市日常節奏的地方。",
    story: "我原本只是想找早餐，結果在市場裡走了很久。熟食、蔬果、攤位聲音和人潮都很自然，不像觀光景點那麼刻意。Sibu 給我的第一印象，就是從這個市場開始的。",
    place: "Sibu Central Market",
    tags: ["Sibu", "Market", "Breakfast", "LocalLife"],
    image: img.market,
    images: gallery(img.market, img.food, img.street)
  },
  {
    id: "review-sibu-night-market",
    city: "sibu",
    name: "Marcus",
    achievement: "探索了 18 個夜市與小吃點",
    title: "晚上來 Sibu Night Market 很剛好",
    description: "不用特別安排很複雜的行程，慢慢吃、慢慢走就很好。",
    story: "我喜歡那種不用想太多的地方。晚上到了 Sibu Night Market，看到攤位和人潮，就知道這裡很適合當作一天的結尾。吃一點小東西，再沿著附近走走，很舒服。",
    place: "Sibu Night Market",
    tags: ["Sibu", "NightMarket", "Food", "SlowTravel"],
    image: img.night,
    images: gallery(img.night, img.market, img.food)
  },
  {
    id: "review-sibu-culture",
    city: "sibu",
    name: "Emily",
    achievement: "記錄了 26 條文化散步路線",
    title: "Sibu 不是只有美食，文化感也很明顯",
    description: "從廟宇、河岸到 Heritage Centre，會慢慢感覺到這座城市的背景。",
    story: "一開始我只知道 Sibu 有 Kampua Mee，但實際走過後，才發現它的文化層次很明顯。河、移民、福州文化、在地生活，全都不是一次看完，而是慢慢浮出來。",
    place: "Sibu Heritage Centre",
    tags: ["Sibu", "Culture", "History", "River"],
    image: img.culture,
    images: gallery(img.culture, img.river, img.street)
  }
];

export const events = [
  {
    id: "sibu-night-market-walk",
    city: "sibu",
    title: "Sibu Night Market Walk",
    date: "每日傍晚後",
    location: "Sibu Night Market",
    desc: "適合晚上慢慢逛，吃小吃、看攤位，也感受 Sibu 的夜間生活感。",
    image: img.night,
    images: gallery(img.night, img.market, img.food)
  },
  {
    id: "sibu-market-morning",
    city: "sibu",
    title: "Sibu Market Morning",
    date: "早晨至中午",
    location: "Sibu Central Market",
    desc: "從市場早餐開始，比直接跑景點更能進入 Sibu 的日常。",
    image: img.market,
    images: gallery(img.market, img.food, img.street)
  },
  {
    id: "sibu-river-evening",
    city: "sibu",
    title: "Rejang River Evening Walk",
    date: "傍晚時段",
    location: "Rejang River, Sibu",
    desc: "沿著河邊慢慢走，看城市光線變化，是 Sibu 很舒服的收尾方式。",
    image: img.river,
    images: gallery(img.river, img.street, img.nature)
  }
];

export const moodConfig = {
  relax: {
    title: "適合放鬆的地方",
    note: "今天適合先找一個安靜、不太趕的地方。"
  },
  food: {
    title: "現在適合吃的地方",
    note: "先吃一頓穩的，比急著跑景點更重要。"
  },
  view: {
    title: "適合看風景的地方",
    note: "這些地方比較適合拍照、看夕陽、慢慢走。"
  },
  hidden: {
    title: "比較小眾的地方",
    note: "避開熱門路線，找一些更像當地朋友會推薦的地方。"
  }
};